"""empty message

Revision ID: d50c3b8f2e38
Revises: fbaa1c23b4d7
Create Date: 2017-04-04 10:27:37.987655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50c3b8f2e38'
down_revision = 'fbaa1c23b4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config_notify', sa.Column('name', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'config_notify', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'config_notify', type_='unique')
    op.drop_column('config_notify', 'name')
    # ### end Alembic commands ###
